// Define the impact relationships between drivers and outcomes
export const driverOutcomeRelationships = {
  // Cost Drivers
  "cost.labor": ["ebitda", "laborCost"],
  "cost.energy": ["ebitda", "energyCost"],
  "cost.maintenance": ["ebitda", "maintenanceCost"],
  "cost.marketing": ["ebitda", "marketingCost", "attendance", "revenue"],
  "cost.administrative": ["ebitda"],
  "cost.foodBeverage": ["ebitda", "perCapita"],
  "cost.retail": ["ebitda", "perCapita"],
  "cost.entertainment": ["ebitda", "attendance"],
  "cost.technology": ["ebitda", "perCapita"],
  "cost.ipLicensing": ["ebitda", "attendance"],
  "cost.facility": ["ebitda"],

  // Revenue Drivers
  "revenue.admission": ["revenue", "perCapita", "ebitda"],
  "revenue.foodBeverage": ["revenue", "perCapita", "ebitda"],
  "revenue.retail": ["revenue", "perCapita", "ebitda"],
  "revenue.media": ["revenue", "perCapita", "ebitda"],
  "revenue.premiumExperience": ["revenue", "perCapita", "ebitda"],
  "revenue.ancillary": ["revenue", "perCapita", "ebitda"],
  "revenue.event": ["revenue", "attendance", "ebitda"],
  "revenue.partnership": ["revenue", "ebitda"],
  "revenue.accommodation": ["revenue", "ebitda"],
  "revenue.digital": ["revenue", "perCapita", "ebitda"],

  // External Drivers
  "external.weather": ["attendance", "revenue", "operatingDays", "ebitda", "energyCost"],
  "external.economic": ["attendance", "revenue", "perCapita", "ebitda"],
  "external.competitive": ["attendance", "revenue", "perCapita"],
  "external.seasonal": ["attendance", "revenue", "operatingDays"],
  "external.regulatory": ["ebitda", "laborCost", "operatingDays"],
  "external.travel": ["attendance", "revenue"],
  "external.health": ["attendance", "revenue", "operatingDays"],
  "external.social": ["attendance", "revenue", "perCapita"],
  "external.technological": ["perCapita", "revenue", "ebitda"]
}

// Impact factors - how much each driver affects each outcome
export const impactFactors = {
  // Cost Driver Impacts
  "cost.labor.ebitda": -0.8,
  "cost.labor.laborCost": 1.0,
  "cost.energy.ebitda": -0.3,
  "cost.energy.energyCost": 1.0,
  "cost.maintenance.ebitda": -0.4,
  "cost.maintenance.maintenanceCost": 1.0,
  "cost.marketing.ebitda": -0.2,
  "cost.marketing.marketingCost": 1.0,
  "cost.marketing.attendance": 0.5,
  "cost.marketing.revenue": 0.4,
  "cost.administrative.ebitda": -0.3,
  "cost.foodBeverage.ebitda": -0.2,
  "cost.foodBeverage.perCapita": -0.1,
  "cost.retail.ebitda": -0.2,
  "cost.retail.perCapita": -0.1,
  "cost.entertainment.ebitda": -0.3,
  "cost.entertainment.attendance": 0.4,
  "cost.technology.ebitda": -0.2,
  "cost.technology.perCapita": 0.1,
  "cost.ipLicensing.ebitda": -0.1,
  "cost.ipLicensing.attendance": 0.2,
  "cost.facility.ebitda": -0.3,

  // Revenue Driver Impacts
  "revenue.admission.revenue": 0.45,
  "revenue.admission.perCapita": 0.6,
  "revenue.admission.ebitda": 0.5,
  "revenue.foodBeverage.revenue": 0.25,
  "revenue.foodBeverage.perCapita": 0.3,
  "revenue.foodBeverage.ebitda": 0.2,
  "revenue.retail.revenue": 0.2,
  "revenue.retail.perCapita": 0.25,
  "revenue.retail.ebitda": 0.15,
  "revenue.media.revenue": 0.1,
  "revenue.media.perCapita": 0.15,
  "revenue.media.ebitda": 0.1,
  "revenue.premiumExperience.revenue": 0.3,
  "revenue.premiumExperience.perCapita": 0.4,
  "revenue.premiumExperience.ebitda": 0.25,
  "revenue.ancillary.revenue": 0.15,
  "revenue.ancillary.perCapita": 0.2,
  "revenue.ancillary.ebitda": 0.1,
  "revenue.event.revenue": 0.2,
  "revenue.event.attendance": 0.3,
  "revenue.event.ebitda": 0.15,
  "revenue.partnership.revenue": 0.1,
  "revenue.partnership.ebitda": 0.1,
  "revenue.accommodation.revenue": 0.15,
  "revenue.accommodation.ebitda": 0.1,
  "revenue.digital.revenue": 0.2,
  "revenue.digital.perCapita": 0.25,
  "revenue.digital.ebitda": 0.15,

  // External Driver Impacts
  "external.weather.attendance": -0.3,
  "external.weather.revenue": -0.25,
  "external.weather.operatingDays": -0.15,
  "external.weather.ebitda": -0.35,
  "external.weather.energyCost": 0.2,
  "external.economic.attendance": -0.2,
  "external.economic.revenue": -0.15,
  "external.economic.perCapita": -0.1,
  "external.economic.ebitda": -0.25,
  "external.competitive.attendance": -0.15,
  "external.competitive.revenue": -0.1,
  "external.competitive.perCapita": -0.05,
  "external.seasonal.attendance": 0.2,
  "external.seasonal.revenue": 0.15,
  "external.seasonal.operatingDays": 0.1,
  "external.regulatory.ebitda": -0.2,
  "external.regulatory.laborCost": 0.15,
  "external.regulatory.operatingDays": -0.1,
  "external.travel.attendance": 0.25,
  "external.travel.revenue": 0.2,
  "external.health.attendance": -0.2,
  "external.health.revenue": -0.15,
  "external.health.operatingDays": -0.1,
  "external.social.attendance": 0.15,
  "external.social.revenue": 0.1,
  "external.social.perCapita": 0.05,
  "external.technological.perCapita": 0.1,
  "external.technological.revenue": 0.15,
  "external.technological.ebitda": 0.1
}

export const relationships: Record<string, number> = {
  // Financial Relationships
  "revenue.tickets.attendance": 1.0,
  "revenue.tickets.price": 1.0,
  "revenue.food.attendance": 0.8,
  "revenue.retail.attendance": 0.6,
  "cost.labor.attendance": 0.7,
  "cost.maintenance.attendance": 0.4,
  "cost.energy.attendance": 0.5,
  "cost.energy.energyCost": 1.0,
  "cost.energy.ebitda": -0.3,
  "cost.energy.waterConsumption": 0.4,
  "cost.energy.wasteManagement": 0.3,
  
  // Environmental Impact Relationships
  "external.weather.energyCost": 0.2,
  "external.weather.waterConsumption": 0.3,
  "external.weather.attendance": -0.15,
  "external.temperature.energyCost": 0.25,
  "external.temperature.waterConsumption": 0.2,
  "external.temperature.attendance": -0.1,
  "external.rainfall.waterConsumption": 0.4,
  "external.rainfall.attendance": -0.2,
  
  // Sustainability Metrics Relationships
  "sustainability.waterConsumption.energyCost": 0.3,
  "sustainability.waterConsumption.wasteManagement": 0.2,
  "sustainability.wasteManagement.energyCost": 0.25,
  "sustainability.renewableEnergy.energyCost": -0.4,
  "sustainability.renewableEnergy.carbonEmissions": -0.5,
  "sustainability.carbonEmissions.energyCost": 0.35,
  "sustainability.carbonEmissions.wasteManagement": 0.3,
  
  // Circular Economy Relationships
  "circularEconomy.materialRecovery.wasteManagement": -0.3,
  "circularEconomy.materialRecovery.energyCost": -0.2,
  "circularEconomy.recycling.wasteManagement": -0.25,
  "circularEconomy.recycling.energyCost": -0.15,
  "circularEconomy.reuse.wasteManagement": -0.2,
  "circularEconomy.reuse.energyCost": -0.1
}

