import type { Scenario } from "./types"

// Sample scenarios
export const sampleScenarios: Scenario[] = [
  {
    id: "baseline-2025",
    name: "Baseline 2025",
    description: "Standard projection for 2025 season",
    lastUpdated: "Apr 2, 2025",
    type: "baseline",
    scope: "all",
    driverValues: {},
    outcomes: {
      attendance: { value: 3.2, percentChange: 0 },
      revenue: { value: 245.8, percentChange: 0 },
      perCapita: { value: 76.81, percentChange: 0 },
      operatingDays: { value: 365, percentChange: 0 },
      ebitda: { value: 98.3, percentChange: 0 },
    },
    assumptions: [
      {
        id: "assumption-1",
        category: "Economic",
        description: "GDP Growth Rate",
        value: 2.5,
        unit: "%",
        source: "Federal Reserve",
        lastUpdated: "Apr 2, 2025",
        notes: "Based on latest economic projections",
      },
      {
        id: "assumption-2",
        category: "Weather",
        description: "Average Temperature",
        value: 75,
        unit: "°F",
        source: "Historical Data",
        lastUpdated: "Apr 2, 2025",
        notes: "Based on 10-year average",
      },
    ],
    versions: [
      {
        id: "version-1",
        version: 1,
        createdAt: "Apr 1, 2025",
        createdBy: "John Doe",
        changes: "Initial baseline scenario creation",
        scenario: {} as Scenario, // Circular reference, will be populated at runtime
      },
    ],
    status: "approved",
    approvedBy: "Jane Smith",
    approvedAt: "Apr 2, 2025",
  },
  {
    id: "optimistic-growth",
    name: "Optimistic Growth",
    description: "Projection with favorable conditions",
    lastUpdated: "Apr 1, 2025",
    type: "optimistic",
    scope: "all",
    driverValues: {
      "revenue.admission": 8.5,
      "revenue.foodBeverage": 3.8,
      "revenue.retail": 2.5,
      "revenue.premiumExperience": 15.0,
      "external.economic": 5.0,
      "external.seasonal": 3.0,
    },
    outcomes: {
      attendance: { value: 3.5, percentChange: 9.4 },
      revenue: { value: 275.2, percentChange: 12.0 },
      perCapita: { value: 78.63, percentChange: 2.4 },
      operatingDays: { value: 365, percentChange: 0 },
      ebitda: { value: 115.6, percentChange: 17.6 },
    },
    assumptions: [
      {
        id: "assumption-3",
        category: "Economic",
        description: "GDP Growth Rate",
        value: 3.5,
        unit: "%",
        source: "Optimistic Forecast",
        lastUpdated: "Apr 1, 2025",
        notes: "Above-trend growth scenario",
      },
      {
        id: "assumption-4",
        category: "Marketing",
        description: "Marketing Budget Increase",
        value: 15,
        unit: "%",
        source: "Marketing Plan",
        lastUpdated: "Apr 1, 2025",
        notes: "Increased digital marketing spend",
      },
    ],
    versions: [
      {
        id: "version-2",
        version: 1,
        createdAt: "Apr 1, 2025",
        createdBy: "John Doe",
        changes: "Initial optimistic scenario creation",
        scenario: {} as Scenario, // Circular reference, will be populated at runtime
      },
    ],
    status: "pending_review",
  },
  {
    id: "conservative-outlook",
    name: "Conservative Outlook",
    description: "Projection with cautious assumptions",
    lastUpdated: "Mar 28, 2025",
    type: "conservative",
    scope: "all",
    driverValues: {
      "revenue.admission": -5.0,
      "revenue.foodBeverage": -2.0,
      "external.economic": -3.0,
      "external.competitive": 4.0,
      "cost.labor": 3.2,
      "cost.energy": 2.8,
    },
    outcomes: {
      attendance: { value: 2.9, percentChange: -9.4 },
      revenue: { value: 220.1, percentChange: -10.5 },
      perCapita: { value: 75.9, percentChange: -1.2 },
      operatingDays: { value: 350, percentChange: -4.1 },
      ebitda: { value: 82.5, percentChange: -16.1 },
    },
    assumptions: [
      {
        id: "assumption-5",
        category: "Economic",
        description: "GDP Growth Rate",
        value: 1.5,
        unit: "%",
        source: "Conservative Forecast",
        lastUpdated: "Mar 28, 2025",
        notes: "Below-trend growth scenario",
      },
      {
        id: "assumption-6",
        category: "Competition",
        description: "New Competitor Impact",
        value: -8,
        unit: "%",
        source: "Market Analysis",
        lastUpdated: "Mar 28, 2025",
        notes: "New theme park opening in region",
      },
    ],
    versions: [
      {
        id: "version-3",
        version: 1,
        createdAt: "Mar 28, 2025",
        createdBy: "John Doe",
        changes: "Initial conservative scenario creation",
        scenario: {} as Scenario, // Circular reference, will be populated at runtime
      },
    ],
    status: "rejected",
    rejectedBy: "Jane Smith",
    rejectedAt: "Mar 29, 2025",
    rejectionReason: "Assumptions too conservative, please revise with more moderate economic outlook",
  },
  {
    id: "weather-impact",
    name: "Weather Impact Analysis",
    description: "Projection with adverse weather conditions",
    lastUpdated: "Mar 25, 2025",
    type: "weather",
    scope: "all",
    driverValues: {
      "external.weather": 8.0,
      "cost.energy": 5.0,
    },
    outcomes: {
      attendance: { value: 2.8, percentChange: -12.5 },
      revenue: { value: 212.4, percentChange: -13.6 },
      perCapita: { value: 75.86, percentChange: -1.2 },
      operatingDays: { value: 345, percentChange: -5.5 },
      ebitda: { value: 76.4, percentChange: -22.3 },
    },
    assumptions: [
      {
        id: "assumption-7",
        category: "Weather",
        description: "Rainy Days",
        value: 45,
        unit: "days",
        source: "Weather Forecast",
        lastUpdated: "Mar 25, 2025",
        notes: "Above average rainfall expected",
      },
      {
        id: "assumption-8",
        category: "Energy",
        description: "Energy Cost Increase",
        value: 12,
        unit: "%",
        source: "Utility Forecast",
        lastUpdated: "Mar 25, 2025",
        notes: "Higher cooling costs due to extreme temperatures",
      },
    ],
    versions: [
      {
        id: "version-4",
        version: 1,
        createdAt: "Mar 25, 2025",
        createdBy: "John Doe",
        changes: "Initial weather impact scenario creation",
        scenario: {} as Scenario, // Circular reference, will be populated at runtime
      },
    ],
    status: "approved",
    approvedBy: "Jane Smith",
    approvedAt: "Mar 26, 2025",
  },
]

